=== DBCooper2012/fuse-extra/fabric-apollo-amqp/fabric-apollo-amqp-codec/src/main/resources/amqp/amqp.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright (C) FuseSource, Inc.
  http://fusesource.com

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<!ELEMENT amqp (doc|section)*>
<!ATTLIST amqp
          xmlns CDATA #IMPLIED
          name CDATA #REQUIRED
	  label CDATA #IMPLIED
>

<!ELEMENT section (doc|definition|type)*>
<!ATTLIST section
          name CDATA #REQUIRED
          title CDATA #IMPLIED
          label CDATA #IMPLIED
>

<!ELEMENT definition (doc)*>
<!ATTLIST definition
	  name CDATA #REQUIRED
	  value CDATA #REQUIRED
	  label CDATA #IMPLIED
>

<!ELEMENT type (encoding|descriptor|field|choice|doc)*>
<!ATTLIST type
          name CDATA #REQUIRED
          class (primitive|composite|restricted|union) #REQUIRED
          source CDATA #IMPLIED
          provides CDATA #IMPLIED
          label CDATA #IMPLIED
>

<!ELEMENT encoding (doc)*>
<!ATTLIST encoding
          name CDATA #IMPLIED
          label CDATA #IMPLIED
          code CDATA #REQUIRED
          category (fixed|variable|compound|array) #REQUIRED
          width CDATA #IMPLIED
>


<!ELEMENT descriptor (doc)*>
<!ATTLIST descriptor
          name CDATA #IMPLIED
          code CDATA #IMPLIED
>

<!ELEMENT field (doc)*>
<!ATTLIST field
	  name CDATA #REQUIRED
	  type CDATA #IMPLIED
          requires CDATA #IMPLIED
          default CDATA #IMPLIED
          label CDATA #IMPLIED
          mandatory CDATA #IMPLIED
          multiple CDATA #IMPLIED
>

<!ELEMENT choice (doc)*>
<!ATTLIST choice
          name CDATA #REQUIRED
          value CDATA #REQUIRED
>

<!ELEMENT doc (doc|p|ul|ol|dl|picture)*>
<!ATTLIST doc
          name CDATA #IMPLIED
	  title CDATA #IMPLIED
>

<!ELEMENT p (#PCDATA|anchor|xref|b|i|term|todo|sup|sub|br)*>
<!ATTLIST p
          title CDATA #IMPLIED
>

<!ELEMENT xref (#PCDATA)>
<!ATTLIST xref
          type CDATA #IMPLIED
          name CDATA #REQUIRED
          choice CDATA #IMPLIED
>

<!ELEMENT anchor (#PCDATA)>
<!ATTLIST anchor
          name CDATA #REQUIRED
>

<!ELEMENT br EMPTY>

<!ELEMENT b (#PCDATA|sub|sup|i|br|anchor)*>
<!ELEMENT i (#PCDATA|sub|sup|b|br|anchor)*>
<!ELEMENT term (#PCDATA)>
<!ELEMENT todo (#PCDATA)>
<!ATTLIST todo
          class (presentation|content|intent) #IMPLIED>
<!ELEMENT sup (#PCDATA|sup|sub|b|i)*>
<!ELEMENT sub (#PCDATA|sup|sub|b|i)*>

<!ELEMENT ul (li)*>
<!ATTLIST ul
	  title CDATA #IMPLIED
>
<!ELEMENT ol (li)*>
<!ATTLIST ol
	  title CDATA #IMPLIED
>

<!ELEMENT li (#PCDATA|p|ul|dl)*>

<!ELEMENT dl (dt, dd)*>
<!ATTLIST dl
	  title CDATA #IMPLIED
>
<!ELEMENT dt (#PCDATA)>
<!ELEMENT dd (p|picture|ul|ol)*>

<!ELEMENT picture (#PCDATA)>
<!ATTLIST picture
	  title CDATA #IMPLIED
>

=== DBCooper2012/fuse-extra/fusemq-apollo/fabric-apollo-amqp/fabric-apollo-amqp-codec/src/main/resources/amqp/security.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="amqp.xsl"?>

<!--
  Copyright (C) FuseSource, Inc.
  http://fusesource.com

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<!DOCTYPE amqp SYSTEM "amqp.dtd">

<amqp name="security" label="the AMQP Security Layers">

  <section name="security-layers" title="Security Layers" label="Security Layers">
    <doc>
      <p>
        Security Layers are used to establish an authenticated and/or encrypted transport over which
        regular AMQP traffic can be tunneled. Security Layers may be tunneled over one another (for
        instance a Security Layer used by the peers to do authentication may be tunneled over a
        Security Layer established for encryption purposes).
      </p>

      <p>
        The framing and protocol definitions for security layers are expected to be defined
        externally to the AMQP specification as in the case of TLS
        [<xref name="RFC5246">RFC5246</xref>]. An exception to this is the SASL
        [<xref name="RFC4422">RFC4422</xref>]
        security layer which depends on its host protocol to provide framing. Because of this we
        define the frames necessary for SASL to function in <xref name="sasl"/> below. When a
        security layer terminates (either before or after a secure tunnel is established), the TCP
        Connection MUST be closed by first shutting down the outgoing stream and then reading the
        incoming stream until it is terminated.
      </p>
    </doc>
  </section>

  <section name="tls" title="TLS" label="TLS Security Layer">
    <doc>
      <p>
        To establish a TLS tunnel, each peer MUST start by sending a protocol header. The protocol
        header consists of the upper case ASCII letters "AMQP" followed by a protocol id of two,
        followed by three unsigned bytes representing the major, minor, and revision of the
        specification version (currently <xref name="TLS-MAJOR"/>, <xref name="TLS-MINOR"/>,
        <xref name="TLS-REVISION"/>). In total this is an 8-octet sequence:
      </p>

      <picture><![CDATA[
  4 OCTETS   1 OCTET   1 OCTET   1 OCTET   1 OCTET
+----------+---------+---------+---------+----------+
|  "AMQP"  |   %d2   |  major  |  minor  | revision |
+----------+---------+---------+---------+----------+]]>
      </picture>

      <p>
        Other than using a protocol id of two, the exchange of TLS tunnel headers follows the same
        rules specified in the version negotiation section of the transport specification (See
        <xref type="section" name="version-negotiation"/>).
      </p>
    </doc>

    <doc>
      <p>
        The following diagram illustrates the interaction involved in creating a TLS Security Layer:
      </p>
      <picture><![CDATA[
TCP Client                 TCP Server
=========================================
AMQP%d2.1.0.0  --------->
               <---------  AMQP%d2.1.0.0
                    :
                    :
            <TLS negotiation>
                    :
                    :
AMQP%d0.1.0.0  --------->                (over TLS secured connection)
               <---------  AMQP%d0.1.0.0
         open  --------->
               <---------  open ]]>
      </picture>

      <p>
        When the use of the TLS Security Layer is negotiated, the following rules apply:
      </p>

      <ul>
        <li>
          <p>
            The TLS client peer and TLS server peer are determined by the TCP client peer and TCP
            server peer respectively.
          </p>
        </li>

        <li>
          <p>
            The TLS client peer SHOULD use the server name indication extension as described in
            RFC-4366 [<xref name="RFC4366">RFC4366</xref>].
            If it does so, then it is undefined what happens if this
            differs to hostname in the <xref type="type" name="sasl-init"/> and
            <xref type="type" name="open"/> frame frames.
          </p>
          <p>
            This field can be used by AMQP proxies to determine the correct back-end service to
            connect the client to, and to determine the domain to validate the client's
            credentials against if TLS client certificates are being used.
          </p>
        </li>

        <li>
          <p>
            The TLS client MUST validate the certificate presented by the TLS server.
          </p>
        </li>

        <li>
          <p>
            Implementations MAY choose to use TLS with unidirectional shutdown, i.e. an application
            initiating shutdown using close_notify is not obliged to wait for the peer to respond,
            and MAY close the write-half of the TCP socket.
          </p>
        </li>
      </ul>
    </doc>

    <doc title="Alternative Establishment">
      <p>
        In certain situations, such as connecting through firewalls, it may not be possible to
        establish a TLS security layer using tunnelling. This might be because a deep packet
        inspecting firewall sees the first few bytes of the connection 'as not being TLS'.
      </p>

      <p>
        As an alternative, implementations MAY run a pure TLS server, i.e., one that does not
        expect the tunnel negotiation handshake. The IANA service name for this is amqps and the
        port is <xref name="SECURE-PORT"/> (5671). Implementations may also choose to run this pure
        TLS server on other ports, should this be operationally required (e.g. to tunnel through a
        legacy firewall that only expects TLS traffic on port 443).
       </p>
    </doc>

    <definition name="TLS-MAJOR" value="1" label="major protocol version" />
    <definition name="TLS-MINOR" value="0" label="minor protocol version" />
    <definition name="TLS-REVISION" value="0" label="protocol revision" />

  </section>

  <!-- == Section: sasl ======================================================================== -->

  <section name="sasl" title="SASL" label="SASL Security Layer">
    <doc>
      <p>
        To establish a SASL tunnel, each peer MUST start by sending a protocol header. The protocol
        header consists of the upper case ASCII letters "AMQP" followed by a protocol id of three,
        followed by three unsigned bytes representing the major, minor, and revision of the
        specification version (currently <xref name="SASL-MAJOR"/>, <xref name="SASL-MINOR"/>,
        <xref name="SASL-REVISION"/>). In total this is an 8-octet sequence:
      </p>

      <picture><![CDATA[
  4 OCTETS   1 OCTET   1 OCTET   1 OCTET   1 OCTET
+----------+---------+---------+---------+----------+
|  "AMQP"  |   %d3   |  major  |  minor  | revision |
+----------+---------+---------+---------+----------+]]>
      </picture>

      <p>
        Other than using a protocol id of three, the exchange of SASL tunnel headers follows the
        same rules specified in the version negotiation section of the transport specification (See
        <xref type="section" name="version-negotiation"/>).
      </p>

      <p>
        The following diagram illustrates the interaction involved in creating a SASL Security
        Layer:
      </p>

      <picture><![CDATA[
TCP Client                 TCP Server
=========================================
AMQP%d3.1.0.0  --------->
               <---------  AMQP%d3.1.0.0
                    :
                    :
            <SASL negotiation>
                    :
                    :
AMQP%d0.1.0.0  --------->                (over SASL secured connection)
               <---------  AMQP%d0.1.0.0
         open  --------->
               <---------  open ]]>
      </picture>
    </doc>

    <doc title="SASL Frames">
       <p>
         SASL performatives are framed as per <xref type="section" name="framing"/>. A SASL frame
         has a type code of 0x01. Bytes 6 and 7 of the header are ignored. Implementations SHOULD
         set these to 0x00. The extended header is ignored. Implementations SHOULD therefore set
         DOFF to 0x02.
       </p>

      <picture title="SASL Frame"><![CDATA[
              type: 0x01 - SASL frame

           +0       +1       +2       +3
       +-----------------------------------+ -.
     0 |                SIZE               |  |
       +-----------------------------------+  |---> Frame Header
     4 |  DOFF  |  TYPE  |   <IGNORED>*1   |  |      (8 bytes)
       +-----------------------------------+ -'
       +-----------------------------------+ -.
     8 |                ...                |  |
       .                                   .  |---> Extended Header
       .             <IGNORED>*2           .  |  (DOFF * 4 - 8) bytes
       |                ...                |  |
       +-----------------------------------+ -'
       +-----------------------------------+ -.
4*DOFF |                                   |  |
       .                                   .  |
       .                                   .  |
       .    Sasl Mechanisms / Sasl Init    .  |
       .   Sasl Challenge / Sasl Response  .  |---> Frame Body
       .           Sasl Outcome            .  |  (SIZE - DOFF * 4) bytes
       .                                   .  |
       .                                   .  |
       .                           ________|  |
       |                ...       |           |
       +--------------------------+          -'

        *1 SHOULD be set to 0x0000
        *2 Ignored, so DOFF should be set to 0x02 ]]>
      </picture>

      <p>
